### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by generationmake**

### CODE REVIEW

**Comment by generationmake** [comment]
add I2C eeprom

**Comment by generationmake** [comment]
Good morning @aentinger
any comments on this one?
Do we need a I2C eeprom for cyphal functions or do we have other options with the R4?

**Comment by aentinger** [comment]
Hi @generationmake ☕ 👋 

A couple oft thoughts:

- 3-pin connectors and real jumper instead of 0R solder jumpers
- Does the 24LC64 not tolerate 5V, do we really need those level shifters?
- Can the WiFi/Minima be backpowered via 5V pin? Please check original schematic of those boards.

**Comment by generationmake** [comment]
Hi @aentinger 

I updated the design.

The solder jumpers were replaced by real jumpers.
CAN driver and I2C eeprom were switched to real 5V devices.
The I2C level shifter circuit is only necessary if the Qwiic connctor is used because this one is a 3.3 V connector. The same circuit is on the Arduino Uno R4 WiFi.
And yes, I think it is possible to back power the Arduino Uno R4 by the 5V pin. The same is done, when the board is connected via USB.

**Comment by aentinger** [comment]
Looks good to me!

Maybe add a 120R termination plus jumper if you're fancy (instead of just providing the possibility to solder the termination resistor in), otherwise this is good to go to production I think.

**Comment by aentinger** [comment]
Please export a new schematic ;)

**Comment by generationmake** [comment]
Hi @aentinger 
I will update the data this weekend.
FYI: I sent the PCB to the manufacturer this morning.

**Pull request merged**
